name: Lucas Eduardo Melzi
description: Criei este blog para trazer alguns estudos que estou realizando, escrever um pouco sobre o que estou aprendendo e também poder compartilhar artigos sobre área de tecnologia
meta_description: "Studies, datascience"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Lucas Eduardo Melzi'
