name: Lucas Eduardo Melzi
description: Criei essa página com próposito de trazer alguns estudos que estou realizando e também poder compartilhar artigos sobre a área de tecnologia e afins
meta_description: "Studies, datascience"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://melzilucas.github.io'
google_analytics: 'UA-164026118-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://melzilucas.github.io'
author:         'Lucas Eduardo Melzi'

plugins_dir:
  - jekyll-seo-tag

social_links:
  LinkedIn: https://www.linkedin.com/in/lucas-eduardo-melzi/
  GitHub: https://github.com/melzilucas
  Twitter: https://twitter.com/LucasMelzi
  instagram: https://www.instagram.com/melzilucas/

twitter:
  username: LucasMelzi

port: 4444